### ISSUE TITLE
Windows: the system cannot find the path specified.

### ISSUE THREAD

**Issue by aminya** [oprogramador/fast-rimraf#1]
Running this on a simple example give the following error:
```
❯ npx fast-rimraf .\node_modules\
The system cannot find the path specified.
```

**Comment by oprogramador** [comment]
Sorry for a late response and still I don't have time to fix this.

For me the following works:
```
# go to your home directory
yarn add fast-rimraf
# go to any directory
bash ~/node_modules/.bin/fast-rimraf path-to-directory-you-want-to-remove
```

**Comment by aminya** [comment]
That requires bash. The point of not using `rm -rf` itself directly is because it is not cross-platform.
You should rewrite the code using a cross-platform library such as shx:

https://github.com/shelljs/shx/
